################################
# Site Settings
################################
lang        : "en"
logo        :
title       : "JAM"
description : "Your awesome site"
author      : "Joe Bloggs"
email       : "hello@example.com"
newsletter  : "http://eepurl.com/cKS1on"
baseurl     : "" # the subpath of your site, e.g. /blog
url         : "https://example.com"
date_format : "%-d %B %Y"
port        : 4000


################################
# Theme Settings
################################
theme       : jekyll-theme-jam
permalink   : /:title/

# Disqus Comments
disqus:
    # Leave shortname blank to disable comments site-wide.
    # Disable comments for any post by adding `comments: false` to that post's YAML Front Matter.
    shortname: desired-persona-dev

markdown: kramdown
kramdown:
    input: GFM
    hard_wrap: false
    syntax_highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style

# Include/Exclude filetypes
include:
  - _pages

exclude:
  - Gemfile.lock
  - node_modules
  

################################
# Analytics Settings
################################
google_analytics:
google_tag_manager:


################################
# Jekyll Plugins
################################
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed


# Jekyll SEO Tag Settings https://github.com/jekyll/jekyll-seo-tag
disable_title_output: true # Removes "| site title" from page <title> tag.

social:
  name: full name
  links:
    - https://twitter.com/username
    - https://plus.google.com/+username
    - https://www.facebook.com/username

twitter:
  username: username

webmaster_verifications:
  google:
  bing:
  alexa:
  yandex:


# Jekyll Feed Settings https://github.com/jekyll/jekyll-feed
atom_feed:
    path: # Leave blank to use default (feed.xml)